// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUMJJ7RtvdM6Ws-q5QxOun0C1FzJ1hC_s',
    appId: '1:94473476184:web:48ec5f4d74368930f5922d',
    messagingSenderId: '94473476184',
    projectId: 'kcal-a6664',
    authDomain: 'kcal-a6664.firebaseapp.com',
    storageBucket: 'kcal-a6664.firebasestorage.app',
    measurementId: 'G-1LH8H784ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn_46hfxzb9SXsET4pnCdN1-_jI_sis1A',
    appId: '1:94473476184:android:776b17f3cd3da8a5f5922d',
    messagingSenderId: '94473476184',
    projectId: 'kcal-a6664',
    storageBucket: 'kcal-a6664.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtI8Uhh1x6P53DuF0Q10_p0gjq-nWG3bA',
    appId: '1:94473476184:ios:3eb1adac240609d0f5922d',
    messagingSenderId: '94473476184',
    projectId: 'kcal-a6664',
    storageBucket: 'kcal-a6664.firebasestorage.app',
    iosBundleId: 'com.example.calorieCalculation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtI8Uhh1x6P53DuF0Q10_p0gjq-nWG3bA',
    appId: '1:94473476184:ios:3eb1adac240609d0f5922d',
    messagingSenderId: '94473476184',
    projectId: 'kcal-a6664',
    storageBucket: 'kcal-a6664.firebasestorage.app',
    iosBundleId: 'com.example.calorieCalculation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUMJJ7RtvdM6Ws-q5QxOun0C1FzJ1hC_s',
    appId: '1:94473476184:web:dba2627d9ee1cc7df5922d',
    messagingSenderId: '94473476184',
    projectId: 'kcal-a6664',
    authDomain: 'kcal-a6664.firebaseapp.com',
    storageBucket: 'kcal-a6664.firebasestorage.app',
    measurementId: 'G-M21VSMSMJM',
  );

}